name = "luggsters-website"
main = "payment-server.js"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."

[env.production]
name = "luggsters-website-production"
route = "luggsters.com/*"

[env.production.vars]
ENVIRONMENT = "production"

[env.staging]
name = "luggsters-website-staging"
route = "staging.luggsters.com/*"

[env.staging.vars]
ENVIRONMENT = "staging"

[vars]
ENVIRONMENT = "development"

[[kv_namespaces]]
binding = "LUGGSTERS_KV"
id = ""
preview_id = ""

[[services]]
binding = "PAYMENT_SERVICE"
service = "luggsters-payment-service"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"
upstream_protocol = "https"

[[d1_databases]]
binding = "LUGGSTERS_DB"
database_name = "luggsters-database"
database_id = ""

[site]
bucket = "./dist"
entry-point = "workers-site"
include = ["**/*"]
exclude = ["node_modules"]